### Create a new patient
POST http://localhost:4004/api/patients
Authorization: Bearer {{token}}
Content-Type: application/json


{
  "name": "John Doe with billing account",
  "email": "johndoe.billing12@gmail.com",
  "address": "123 Main St",
  "dateOfBirth": "1990-01-01",
  "registeredDate": "2025-01-01"
}
